### ISSUE TITLE
I think dektrium left this repository

### ISSUE THREAD

**Issue by trbsi** [dektrium/yii2-user#621] opened 2016-03-03 21:07 UTC
What do you think?

**Comment by thiagotalma** [comment] 2016-03-04 02:19
@trbsi You tried to send mail to @dmeroff ?

**Comment by yarrgh** [comment] 2016-03-04 04:32
If so. I'd love for someone to fork this repo and start maintaining it

**Comment by trbsi** [comment] 2016-03-04 08:13
I didn't. I'll try

**Comment by tecnologiaterabyte** [comment] 2016-03-07 11:41
@thiagotalma @dmeroff I think the problem is that people want a free professional module without mistakes, nothing collaborate with the project, or pay anything, this discourages any open source initiative.

**Comment by trbsi** [comment] 2016-03-07 11:47
Some of us did collaborate

**Comment by yarrgh** [comment] 2016-03-07 13:55
@thiagotalma what you're saying would actually increase collaboration. Having one person create, maintain, and do everything would increase the chances of needing to pay. There are a ton of open source projects that everyone collaborates with and are very professional.

**Comment by thiagotalma** [comment] 2016-03-07 23:24
https://github.com/dektrium/yii2-user/graphs/contributors
https://github.com/yiisoft/yii2/graphs/contributors

**Comment by yarrgh** [comment] 2016-03-11 20:28
@trbsi Any luck contacting him? No response on my end.

**Comment by trbsi** [comment] 2016-03-11 20:34
I tried, nothing. I guess he left, we are on our own now. At least we have very good foundation of user registration and management for yii2 so we can keep building further

**Comment by yarrgh** [comment] 2016-03-11 22:14
Can't keep building it further unless someone forks it and actively maintains it and/or gives others access to maintain the project as well. Don't want to chance another project going stale.

**Comment by thiagotalma** [comment] 2016-03-12 17:16
It would be great if the @yiisoft staff assume this project (or create a new one).

The management of users and permissions is a vital part of the framework, this should be an official module.

@qiangxue, @cebe, @klimov-paul, @samdark
Hello guys! What do you think about this?

**Comment by trbsi** [comment] 2016-03-12 17:46
I doubt it, it's extra job every time they publish total new version of yii like: 2,3,4,..

**Comment by samdark** [comment] 2016-03-12 22:35
Nope. Won't adopt the project.

**Comment by schmunk42** [comment] 2016-03-16 15:31
Indeed not much activity here: https://github.com/dmeroff :(

Would be really great to get some feedback about the general status.

If anyone starts maintaining a fork, please post your URL/project here.
I think this is one the most popular extensions for Yii2.

**Comment by dmeroff** [comment] 2016-03-19 15:35
Hello guys! I'm really sorry, that I couldn't contribute to yii2-user for a while. I had no time to work on the project and answer to issues. But I think I'll be able to start contributing again in a few days ;)

**Comment by thiagotalma** [comment] 2016-03-19 17:06
Uhu!
Dmitry is alive! 🙌🙌🙌

Welcome back. We where happy to see you.

**Comment by samdark** [comment] 2016-03-19 19:37
@dmeroff seems there's a big interest in the project. I'd recomment adding more maintainers with commit permissions and probably even admin permissions to keep it running when you're too busy.

**Comment by yarrgh** [comment] 2016-03-19 21:45
I second recommending adding others to help with the project.

**Comment by dmeroff** [comment] 2016-03-23 08:17
Thank you for your support. I'll consider adding more maintainers to the project, so Yii2-user will be developed faster.

I also can say that new version (0.9.6) will be released on this weekend!

**Closed by dmeroff** 2016-03-23 08:17 UTC
