### ISSUE TITLE
How to check if user is admin?

### ISSUE THREAD

**Issue by pedroponte** [dektrium/yii2-user#936] opened 2017-06-06 21:33 UTC
### What steps will reproduce the problem?
E.G. Yii::$app->user->isAdmin
### What is the expected result?
true / false
### What do you get instead?
function not available
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      |
| Yii2-user version |
| PHP version       |

**Comment by septemberboy7** [comment] 2017-08-17 18:19
I use something like this.

\dektrium\user\models\User::findOne(['id'=> Yii::$app->user->id])->isAdmin

**Comment by myomyintaung512** [comment] 2017-08-18 07:53
You can use 
```
Yii::$app->user->isGuest; // check if user is guest
Yii::$app->user->identity->isAdmin; // check if user is an admin

```

Duplicate of #201

**Comment by bscheshirwork** [comment] 2018-01-11 08:42
#986

**Closed** 2018-01-11 11:42 UTC
