### ISSUE TITLE
Independent sessions in one domain

### ISSUE THREAD

**Issue by 112Legion112** [dektrium/yii2-user#1017] opened 2018-03-15 08:17 UTC
I think I found a bug in the config file.
I'm using yii2 advanced templed.
I couldn't login in **backend** till I changed the config of the session like follow:

```
        'session' => [
            'name' => 'BACKEND_SESSION_ID', // instend of BACKENDSESSID
            'cookieParams' => [
                'httpOnly' => true,
                'path'     => '/backend/web',
            ],
        ],
```

https://github.com/dektrium/yii2-user/blob/0.9.12/docs/usage-with-advanced-template.md#use-independent-sessions-in-one-domain

**Comment by myomyintaung512** [comment] 2018-03-15 10:27
Duplicate of #430

**Closed** 2018-03-15 12:21 UTC
