### ISSUE TITLE
Problems with yii 2.0.9

### ISSUE THREAD

**Issue by SoleSS** [dektrium/yii2-user#753] opened 2016-08-10 13:09 UTC
### What steps will reproduce the problem?
install clean Yii 2.0.9 with composer
install extension according to manual (don't forget to remove user from components)

### What is the expected result?
registration works
email confirmation works
successull login after confirm
successfull logout
successfull login with login\password

### What do you get instead?
login with form will FAIL

### Additional info
i have and old yii 2.0.5 installation where everything works...

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.9
| Yii2-user version |0.9.8
| PHP version       | 5.6.17

**Comment by dbd5** [comment] 2016-08-11 13:05
+1

**Comment by dmeroff** [comment] 2016-08-11 14:07
I'm sorry, but I cannot reproduce issue.
I've just tried it with clean yii2-app-basic installation.

**Comment by SoleSS** [comment] 2016-08-11 14:17
mb, you can give as all steps, to reproduce?..
because i can't find the reason why it's not working...

**Comment by dmeroff** [comment] 2016-08-11 14:19
@SoleSS I can't give you any special steps. I've just installed fresh yii2-app-basic app and then installed yii2-user as described in guide. And it works as expected.

**Comment by dbd5** [comment] 2016-08-11 14:41
@dmeroff ,

I just want to add this note. 

I can confirm that the issue is valid but it seems that if you change the login URL from **/user/security/login** to **/user/login** and change the logout URL from **/user/security/logout** to **/user/logout** it works.

I suggest you take another look please, thanks

A

**Comment by SoleSS** [comment] 2016-08-11 14:47
@dbd5 
how to do that?..

**Comment by dbd5** [comment] 2016-08-11 15:21
Hi @SoleSS ,

I have the advanced template installed. This is like reverting from the URL in **Yii2-user** documentation to the original urls that came with the advanced template. I can't explain why it works but it does - that's why I suggested that @dmeroff  take another look.

A

**Comment by SoleSS** [comment] 2016-08-12 09:06
looks like it's a php problem...
i have tested on two servers with php: 
1. PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)
2. PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10)

on second server everything works as expected! (on lower php versions works as well!)

@dmeroff , consider checking this!..

**Comment by dmeroff** [comment] 2016-08-12 10:04
@SoleSS I'm sorry, but I'm not going to check this. It's obviously not yii2-user problem, but one of the three following problems:

1) You didn't remove `user` component configuration from your config
2) It's yii2 problem (since yii2-user only uses api provided by Yii2 to log users in), which is unlikely
3) Your server has problems with writing users sessions.

**Comment by dbd5** [comment] 2016-08-12 12:05
Hi @dmeroff ,

Please let me say before hand that we all appreciate the effort that you put into the excellent work you do - secondly, this is not an attempt to make your work harder. I am quite happy to carry out any tests that will help you debug this and determine what is going on if you can advise on what you want us to check.

Looking at the 3 areas you pointed out, I agree we can eliminate Number 2 and perhaps take a closer look at 1 and 3.

In my case, I followed the documentation and removed the default user component from my config. However, in my implementation I inherited dektrium/user and dropped the Inherited component exactly where the original / default user component was.  (See Below)

Secondly - as part of my integration, I followed the Instruction in **Use independent sessions in one domain** to separate the sessions. A while back I found that certain components had issues assessing sessions until I commented out FRONTENDSESSID in the config (See Below)

My Integration seems to be working well except for the anomaly I pointed out yesterday (Changing URL from /user/security/login to /user/login and change the logout URL from /user/security/logout to /user/logout it works.)

Does any of these actions explain why reverting to the old/default URL from Yii2-advanced resolves the issue? Is there anything I should be worried about with the way I have done the Integration?

Thanks
_______________

        'user' => [
            'class'=>'yii\web\User',
            'identityClass' => 'common\models\User',
            'enableSession' => true,
            // 'enableAutoLogin' => true,
            'authTimeout' => 3600,  // 1 Hour

            'identityCookie' => [
                'name'     => '_frontendIdentity',
                'path'     => '/',
                'httpOnly' => true,
            ],
        ],

        'session' => [
            // 'name' => 'FRONTENDSESSID',
            'cookieParams' => [
                'httpOnly' => true,
                'path'     => '/',
            ],
        ],


The following is the declaration of my user class
...
use dektrium\user\models\User as BaseUser;

class User extends BaseUser
{

**Comment by dmeroff** [comment] 2016-08-12 13:24
/user/security/login and /user/login are pointing to the same controller and action (/user/login is defined as url rule) so I don't really understand how this is a thing.
You overridden user model, did you change it in modules's model map?
If you could create test project on which problem is reproducable, and then send it me, then I'll try to review it on weekend.

**Comment by dbd5** [comment] 2016-08-15 15:15
Hi @dmeroff ,

Thank you for your response.

- Yes, I changed the model map.

I spent the whole of the weekend looking at this again but unfortunately I could not reproduce it on a fresh install of Yii2-advanced. This lead me to look at other possibilities.

I eventually found that I had a number of conflicting rules in my Urlmanager that cause the behaviour I saw. I have now updated my rules and I can positively conclude that the issue has nothing to do with Yii2 or Yii2-user. Please go ahead and close this issue.

Thanks once again!

A

**Closed** 2016-08-15 15:54 UTC
Labels: status: to be verified
